### ISSUE TITLE
是有人玩的!

### ISSUE THREAD

**Issue by YellowTulipShow** [JetLua/colloc#2]
我都打通关了, 想着回来回顾一下, 没想到改数独了...

**Comment by JetLua** [comment]
> 我都打通关了, 想着回来回顾一下, 没想到改数独了...

😂，等有机会我改造一下，变成个小游戏合集。

**Comment by JetLua** [comment]
> 我都打通关了, 想着回来回顾一下, 没想到改数独了...

哥们，回来了。小游戏名：《迷失的心》

**Comment by YellowTulipShow** [comment]
收到, GoGoGo, 游戏做的真不错!

**Comment by JetLua** [comment]
感谢哥们的赞赏，`issue` 也顺手关了。
